#
# Create default command for the target machine
#

machine := $(shell uname -m)

cmdc = $(CC) $(CFLAGS)
cmdx = $(CXX) $(CXXFLAGS)

main_folder := $(shell pwd)
results_folder := $(main_folder)/results
error_log := $(results_folder)/error.log
compile_log := $(results_folder)/compile.log
compile_cmd := $(results_folder)/compile.cmd

